services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      # Pass variables from the .env file as build arguments to the Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    environment:
      - VITE_API_BASE_URL=https://api.resumatch.tnsvc.xyz
    restart: unless-stopped
    

  backend:
    build: ./backend
    restart: unless-stopped
    # Docker Compose automatically reads the .env file in the same directory
    # and makes these variables available to the container.
    environment:
      - SUPABASE_URL=${VITE_SUPABASE_URL} # Use the same public URL
      - SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY} # Use the same public key
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq

  worker:
    build: ./backend
    restart: unless-stopped
    command: node worker.js
    environment:
      - SUPABASE_URL=${VITE_SUPABASE_URL}
      - SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  caddy_data:
  caddy_config:
  rabbitmq_data: